In [44]:
import torch

In [45]:
torch.__version__

'2.5.1'

In [83]:
if torch.cuda.is_available():
    print("GPU availbale")
else:
    print("No GPU.")

No GPU.


## Creating  tensors

In [48]:
## empty
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [49]:
type(a)

torch.Tensor

In [50]:
## zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [51]:
### ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [95]:
### rand
torch.manual_seed(124)
torch.rand(2,3)

tensor([[0.1526, 0.6311, 0.8407],
        [0.4741, 0.5123, 0.1231]])

In [53]:
torch.tensor([[1,2,3],[4,5,6], [7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
torch.arange(0,10,2.3)

tensor([0.0000, 2.3000, 4.6000, 6.9000, 9.2000])

In [55]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [56]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [58]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensors shapes

In [62]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [64]:
## create tensor with the shape of the given tensor
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [66]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [67]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [98]:
torch.manual_seed(124)
torch.rand_like(x,  dtype=torch.float64)

tensor([[0.2209, 0.7256, 0.0981],
        [0.4779, 0.8777, 0.1301]], dtype=torch.float64)

In [72]:
torch.rand_like??

Docstring:
rand_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor with the same size as :attr:`input` that is filled with
random numbers from a uniform distribution on the interval :math:`[0, 1)`.
``torch.rand_like(input)`` is equivalent to
``torch.rand(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, defaults to the device of :attr:`input`.
 

## Tensor data types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [82]:
x.dtype

torch.int64

In [84]:
### make a interger type tensor
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [87]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

tensor([1., 2., 3.])

In [90]:
## convert tensor datatype of an existing tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

In [100]:
### scalar operations
x = torch.rand(2,2)
x

tensor([[0.0827, 0.5029],
        [0.6594, 0.8929]])

In [101]:
x+2

tensor([[2.0827, 2.5029],
        [2.6594, 2.8929]])

In [103]:
torch.ceil(x)

tensor([[1., 1.],
        [1., 1.]])

In [104]:
torch.floor(x)

tensor([[0., 0.],
        [0., 0.]])

In [107]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [110]:
torch.clamp(d, min=2, max=4.1)

tensor([2.0000, 2.3000, 3.7000, 4.1000])

In [118]:
### Reduction operations
e = torch.randint(size=(2,3), low=0, high=6, dtype=torch.float32)
e

tensor([[1., 3., 5.],
        [4., 4., 4.]])

In [119]:
torch.sum(e)

tensor(21.)

In [120]:
torch.mean(e)

tensor(3.5000)

In [124]:
torch.mean(e, dim=1), torch.mean(e, axis=1)

(tensor([3., 4.]), tensor([3., 4.]))

In [177]:
### Matrix operations
vec1 = torch.randint(size=(3,3), low=0, high=6, dtype=torch.float32)
vec2 = torch.randint(size=(3,3), low=0, high=6, dtype=torch.float32)

In [178]:
vec1, vec2

(tensor([[0., 4., 1.],
         [3., 0., 4.],
         [2., 3., 2.]]),
 tensor([[0., 3., 5.],
         [0., 1., 2.],
         [2., 3., 2.]]))

In [179]:
torch.matmul(vec1,vec2)

tensor([[ 2.,  7., 10.],
        [ 8., 21., 23.],
        [ 4., 15., 20.]])

In [180]:
vec3 = torch.tensor([1,2])
vec4 = torch.tensor([3,4])

In [181]:
vec3, vec4

(tensor([1, 2]), tensor([3, 4]))

In [182]:
torch.dot(vec3, vec4)

tensor(11)

In [183]:
## transpose
torch.transpose(vec1, 0, 1)

tensor([[0., 3., 2.],
        [4., 0., 3.],
        [1., 4., 2.]])

In [184]:
torch.det(vec1)

tensor(17.)

In [185]:
torch.inverse(vec1) ## only works on square matrix

tensor([[-0.7059, -0.2941,  0.9412],
        [ 0.1176, -0.1176,  0.1765],
        [ 0.5294,  0.4706, -0.7059]])

## Special functions

In [186]:
vec1

tensor([[0., 4., 1.],
        [3., 0., 4.],
        [2., 3., 2.]])

In [187]:
torch.log(vec1)

tensor([[  -inf, 1.3863, 0.0000],
        [1.0986,   -inf, 1.3863],
        [0.6931, 1.0986, 0.6931]])

In [188]:
torch.exp(vec1)

tensor([[ 1.0000, 54.5982,  2.7183],
        [20.0855,  1.0000, 54.5982],
        [ 7.3891, 20.0855,  7.3891]])

In [189]:
torch.sqrt(vec1)

tensor([[0.0000, 2.0000, 1.0000],
        [1.7321, 0.0000, 2.0000],
        [1.4142, 1.7321, 1.4142]])

In [190]:
torch.sigmoid(vec1)

tensor([[0.5000, 0.9820, 0.7311],
        [0.9526, 0.5000, 0.9820],
        [0.8808, 0.9526, 0.8808]])

In [192]:
torch.softmax(vec1, dim=0)

tensor([[0.0351, 0.7214, 0.0420],
        [0.7054, 0.0132, 0.8438],
        [0.2595, 0.2654, 0.1142]])

In [193]:
torch.relu(vec1)

tensor([[0., 4., 1.],
        [3., 0., 4.],
        [2., 3., 2.]])

## Inplace Operations

In [195]:
m = torch.rand(2,3)
n = torch.rand(2,3)
m,n

(tensor([[0.6646, 0.5060, 0.6224],
         [0.6635, 0.8643, 0.1515]]),
 tensor([[0.3628, 0.0466, 0.5032],
         [0.2872, 0.9346, 0.3320]]))

In [196]:
m+n

tensor([[1.0274, 0.5526, 1.1255],
        [0.9507, 1.7989, 0.4834]])

In [197]:
m.add_(n)

tensor([[1.0274, 0.5526, 1.1255],
        [0.9507, 1.7989, 0.4834]])

In [198]:
m,n

(tensor([[1.0274, 0.5526, 1.1255],
         [0.9507, 1.7989, 0.4834]]),
 tensor([[0.3628, 0.0466, 0.5032],
         [0.2872, 0.9346, 0.3320]]))

In [200]:
torch.relu(m)

tensor([[1.0274, 0.5526, 1.1255],
        [0.9507, 1.7989, 0.4834]])

In [201]:
## inplace change
m.relu_()

tensor([[1.0274, 0.5526, 1.1255],
        [0.9507, 1.7989, 0.4834]])

## Copying Tensor

In [202]:
a = torch.rand(2,3)

In [203]:
b=a

In [205]:
a, b

(tensor([[0.4364, 0.0182, 0.3691],
         [0.3467, 0.4762, 0.6384]]),
 tensor([[0.4364, 0.0182, 0.3691],
         [0.3467, 0.4762, 0.6384]]))

In [206]:
a[0][0] = 0

In [208]:
a,b ## both a and b gets changed

(tensor([[0.0000, 0.0182, 0.3691],
         [0.3467, 0.4762, 0.6384]]),
 tensor([[0.0000, 0.0182, 0.3691],
         [0.3467, 0.4762, 0.6384]]))

In [209]:
id(a), id(b) ## so assignment operator = only refes to the same memory

(5077001104, 5077001104)

In [211]:
## use clone 

b = a.clone()


In [212]:
a[0][0]=10
a,b

(tensor([[10.0000,  0.0182,  0.3691],
         [ 0.3467,  0.4762,  0.6384]]),
 tensor([[0.0000, 0.0182, 0.3691],
         [0.3467, 0.4762, 0.6384]]))

In [213]:
id(a), id(b)

(5077001104, 5076011984)

## Numpy and Pytorch

In [215]:
import numpy as np

In [218]:
## pytorch tensor to numpy array

a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [219]:
b = a.numpy()
b

array([1, 2, 3])

In [220]:
## numpy array to torch tensor
c = np.array([4,5,6])
d = torch.from_numpy(c)
d

tensor([4, 5, 6])