In [22]:
import numpy as np
from tqdm import tqdm
import torch
import torch.nn as nn
from torchinfo import summary

### Simple  logit

![Network Diagram](figs/nn.png)

`nn.Linear(num_features=N, out_features=1)`

$$ z= \mathbf{w}^\top \mathbf{x} + b \quad \text{(logit)} $$
$$ \mathbf{x} \in \mathbb{R}^N, \quad z \in \mathbb{R}^1 $$

`self.sigmoid = nn.Sigmoid()`

$$ \hat{y} = \sigma(z) = \frac{1}{1 + e^{-z}} \in [0,1] $$

`out = self.linear(features)`

$$ \mathcal{M}(\mathbf{x}) = \sigma(\mathbf{w}^\top \mathbf{x} + b) $$


In [13]:
class Model(nn.Module):         # Inherits nn.Module

    def __init__(self, num_features):

        super().__init__()       # Call parent constructor

        self.linear = nn.Linear(num_features, 1) # Linear layer: num_features → 1 logit
        self.sigmoid = nn.Sigmoid()              # Probability [0,1]

    def forward(self, features):
        
        out = self.linear(features)      # x → w*x + b (logit)
        out = self.sigmoid(out)          # logit → probability

        return out
        

In [16]:
## Create fake data (batch of 10 samples, 5 features each)
features = torch.rand(10, 5) # row=10 (observation), col = 5 (features)

##create model
model = Model(features.shape[1])

##call forward pass

model(features)   ## model.forward(features) << also can do this but dont

tensor([[0.6167],
        [0.6610],
        [0.6366],
        [0.6617],
        [0.6277],
        [0.6975],
        [0.6066],
        [0.5802],
        [0.5900],
        [0.6149]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.0628,  0.3100,  0.2271, -0.3754, -0.0889]], requires_grad=True),
 Parameter containing:
 tensor([0.4208], requires_grad=True))

In [24]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [25]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Simple Neural Netwrok with hidden network